### ISSUE TITLE
include token handling code within the published package

### ISSUE THREAD

**Issue by martinxu9** [masenf/reflex-google-auth#1]

**Comment by martinxu9** [comment]
Not sure how useful this code in here is, it's basically the blog post. Also need to update the README

**Comment by dentro-innovation** [comment]
It's the base for the pypi package reflex-google-auth, if you use this package you need to use much less boilerplate code. Install it with `pip install reflex-google-auth`.

**Comment by masenf** [comment]
token handling code is now included and described in the README
